# Generated by Django 5.0.6 on 2024-07-15 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_media_options_alter_media_file'),
        ('news', '0007_rename_created_at_news_create_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.media')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.news')),
            ],
        ),
    ]
