# Generated by Django 5.0.6 on 2024-07-15 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newsimange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimange',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news'),
        ),
    ]
