# Generated by Django 5.0.6 on 2024-07-15 10:15

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_media_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={},
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'gif', 'mp4', 'mp3']), common.validators.file_validator], verbose_name='file'),
        ),
    ]
