# Generated by Django 5.0.6 on 2024-07-16 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_media_options_alter_media_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Mediaes'},
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'gif', 'mp4', 'mp3'])], verbose_name='file'),
        ),
    ]
