# Generated by Django 5.0.6 on 2024-07-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_contactwithus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactWithUs',
        ),
    ]
