# Generated by Django 5.0.6 on 2024-07-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_appinfo_contactus_faq_privacypolicy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='answerbigint',
            new_name='answer',
        ),
    ]
