# Generated by Django 5.0.6 on 2024-07-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_answerbigint_faq_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.CharField(max_length=255, null=True, verbose_name='answerbigint'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='answerbigint'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='answerbigint'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=255, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='question'),
        ),
    ]
